//! Auto-generates `FORCE_LINK` from `Cargo.toml`.
//!
//! Each sibling crate listed under `[dependencies]` (or under
//! `[target.'cfg(target_os = "macos")'.dependencies]`, gated
//! accordingly) gets a fn-pointer entry in `FORCE_LINK`. Consumers
//! linking us call `ensure_linked()` once at startup; that keeps every
//! sibling rlib alive at link time, which keeps each sibling's linkme
//! distributed-slice static alive, which is what
//! `RuntimeContext::with_all_features()` walks.
//!
//! The generated file is emitted to `$OUT_DIR/force_link.rs` and
//! pulled into `src/lib.rs` via `include!()`. Adding a sibling = add
//! one line to `Cargo.toml`; this script regenerates `FORCE_LINK` on
//! the next build. No committed code list to maintain.

use std::env;
use std::fs;
use std::path::PathBuf;

/// Crates we depend on but that should NOT be in `FORCE_LINK`:
/// - `oxideav-core` is the slice host, not a register-emitting sibling.
const SKIP: &[&str] = &["oxideav-core"];

fn main() {
    println!("cargo:rerun-if-changed=Cargo.toml");

    let manifest = fs::read_to_string("Cargo.toml").expect("read Cargo.toml");
    let (general, mac_only) = collect_sibling_deps(&manifest);

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs from Cargo.toml. Do not edit.\n");
    out.push_str("//\n");
    out.push_str("// Each entry is a fn pointer to one sibling's `register` fn. The\n");
    out.push_str("// `#[used]` attribute keeps the static alive through rustc's\n");
    out.push_str("// pre-link DCE pass; `ensure_linked()` (in lib.rs) does a volatile\n");
    out.push_str("// read on it so consumers' main() can give the linker a definite\n");
    out.push_str("// reference.\n");
    out.push_str(
        "\n#[used]\npub static FORCE_LINK: &[fn(&mut oxideav_core::RuntimeContext)] = &[\n",
    );

    for crate_name in &general {
        let krate = crate_name.replace('-', "_");
        out.push_str(&format!("    {krate}::register,\n"));
    }
    for crate_name in &mac_only {
        let krate = crate_name.replace('-', "_");
        out.push_str(&format!("    #[cfg(target_os = \"macos\")]\n"));
        out.push_str(&format!("    {krate}::register,\n"));
    }

    out.push_str("];\n");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR set by cargo"));
    let dest = out_dir.join("force_link.rs");
    fs::write(&dest, out).expect("write force_link.rs");
}

/// Parse `Cargo.toml` for `oxideav-*` deps in `[dependencies]` and in
/// `[target.'cfg(target_os = "macos")'.dependencies]`. Returns
/// `(general, mac_only)` in alphabetical order.
///
/// Hand-rolled mini-TOML parser to avoid pulling the `toml` crate as a
/// build-dep — we only need two specific sections, and the syntax of
/// dependency lines is a small subset.
fn collect_sibling_deps(manifest: &str) -> (Vec<String>, Vec<String>) {
    #[derive(Clone, Copy, PartialEq)]
    enum Section {
        Skip,
        General,
        MacOnly,
    }

    let mut section = Section::Skip;
    let mut general = Vec::<String>::new();
    let mut mac_only = Vec::<String>::new();

    for line in manifest.lines() {
        let trimmed = line.trim();

        if trimmed.starts_with('[') {
            // Section header. Match against the two we care about.
            let header: String = trimmed
                .trim_start_matches('[')
                .trim_end_matches(']')
                .chars()
                .filter(|c| !c.is_whitespace())
                .collect();
            section = if header == "dependencies" {
                Section::General
            } else if header == "target.'cfg(target_os=\"macos\")'.dependencies"
                || header == "target.\"cfg(target_os=\\\"macos\\\")\".dependencies"
            {
                Section::MacOnly
            } else {
                Section::Skip
            };
            continue;
        }

        if section == Section::Skip {
            continue;
        }
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }

        // Look for `crate-name = ...`. Take everything up to the first
        // `=` after stripping whitespace; then trim again.
        let Some(eq) = trimmed.find('=') else {
            continue;
        };
        let key = trimmed[..eq].trim();
        if !key.starts_with("oxideav-") || SKIP.contains(&key) {
            continue;
        }
        // Strip optional trailing comment / TOML-table noise; we only
        // need the bare key.
        let bucket = match section {
            Section::General => &mut general,
            Section::MacOnly => &mut mac_only,
            Section::Skip => unreachable!(),
        };
        bucket.push(key.to_string());
    }

    general.sort();
    mac_only.sort();
    (general, mac_only)
}
