//! Virtual aggregator crate.
//!
//! `oxideav-format-all` declares dependencies on every oxideav sibling
//! codec / container / filter / source crate AND takes a function
//! pointer to each sibling's `register` fn in [`FORCE_LINK`] —
//! **auto-generated by `build.rs` from this crate's own `Cargo.toml`**.
//! Adding a sibling = add one line to `Cargo.toml`; the next build
//! regenerates `FORCE_LINK`. No committed code list to maintain.
//!
//! # Why FORCE_LINK is needed
//!
//! `oxideav_core::REGISTRARS` is a linkme distributed slice. Each
//! sibling crate's `register!()` macro deposits a `Registrar` entry
//! into it via `#[linkme::distributed_slice]` + `#[used]`. In theory,
//! depending on a sibling should be enough to surface its slice entry
//! in the consumer binary. In practice, **rustc's pre-link DCE pass
//! drops whole rlibs whose symbols nothing references** — and the
//! linkme statics inside go with them.
//!
//! The fix:
//!
//! 1. `FORCE_LINK` is a `#[used]` static slice of fn pointers to every
//!    sibling's `register` fn. Referencing each fn keeps each rlib
//!    alive at link time, which keeps each linkme entry alive.
//! 2. [`ensure_linked`] does a volatile read on `FORCE_LINK` so
//!    consumers' `main()` can give the linker a definite reference to
//!    `oxideav-format-all`'s rlib (which keeps `FORCE_LINK` alive,
//!    which keeps every sibling rlib alive, which keeps every linkme
//!    entry alive).
//!
//! Consumers materialise everything by calling
//! [`oxideav_core::RuntimeContext::with_all_features`]:
//!
//! ```ignore
//! use oxideav_core::RuntimeContext;
//!
//! oxideav_format_all::ensure_linked();   // pin the rlibs
//! let ctx = RuntimeContext::with_all_features();
//! // ctx now has every codec / container / filter / source.
//! ```
//!
//! # When to use this crate
//!
//! - You want **everything** the framework supports.
//! - You don't care about binary size.
//!
//! # When NOT to use this crate
//!
//! - You only need a specific subset (e.g. just MP4 + H.264 + AAC).
//!   Depend on the individual sibling crates instead — the slice
//!   walker will see whatever ends up linked.
//! - You're in `no_std` (the slice walker uses `OnceLock` from
//!   `oxideav-core`).
//!
//! # Opt-out at runtime
//!
//! Even when this crate links every sibling, consumers can still skip
//! specific registrars at materialisation time via
//! [`oxideav_core::RuntimeContext::with_all_features_filtered`]. The
//! `oxideav-cli`'s `--no-hwaccel` flag uses this mechanism to suppress
//! `videotoolbox` / `audiotoolbox` registration.

use oxideav_core::RuntimeContext;

// `FORCE_LINK` static — auto-generated by `build.rs` from Cargo.toml.
include!(concat!(env!("OUT_DIR"), "/force_link.rs"));

/// Force-link sentinel — call this once at program startup (typically
/// from `main()`) before [`RuntimeContext::with_all_features`].
///
/// **Why this can't be automated**: Rust's link model only includes
/// rlibs whose symbols something references. A `#[ctor::ctor]` fn or
/// `#[used] static` inside `oxideav-format-all` doesn't help — if no
/// consumer code references any symbol from this rlib, the linker
/// drops the entire rlib (and the ctor / static with it). A build
/// script `cargo:rustc-link-arg=-Wl,-u,SYMBOL` doesn't help either:
/// Cargo applies `rustc-link-arg` from build scripts only to the
/// build-scripted crate's own binaries, never to downstream consumers.
///
/// One short call from `main()` is the smallest possible footprint
/// across every target.
///
/// One call is enough. The fn is a no-op at runtime — pure codegen
/// barrier so LLVM doesn't elide the reference to [`FORCE_LINK`].
#[inline(never)]
pub fn ensure_linked() {
    // Reference FORCE_LINK so the linker can't claim it's unused.
    let ptr: *const &[fn(&mut RuntimeContext)] = &FORCE_LINK;
    // SAFETY: reading our own `'static` slice. Pointer is non-null and
    // initialized at program start.
    unsafe {
        std::ptr::read_volatile(ptr);
    }
}
